Bespin-AF/a2d2-ios

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/ViewControllers/RequestOptionsController.swift
A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift

Added groups size picker to the request pickup options screen and the test to go along with it. SSgt Godsey also pulled from this branch and the test passed so if it doesn't work then I don't know what to say.

Request pickup group size

---

A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift

Refactored UI Tests to follow better coding standards; 
Removed redundant / ineffective test added in commit: fa1bbec0418eb217c5a99cf5b516dc3ec805858c

Refactored UI Tests

---

A2D2_iOS/.gitignore

Hopefully this will end all future merge conflicts. Ignoring .DS_Store and, *.xcuserstate, and *.xcproject. If we need to add or remove some files, we can.

Added a .gitignore to the repo so we can banish files we don't need.

---

A2D2_iOS/A2D2_iOS/ViewControllers/RequestOptionsController.swift

Added validation to make sure name and phone are not empty.

Pickup request bug squash

---

A2D2_iOS/A2D2_iOS/Base.lproj/Main.storyboard

Constrains now make UI Look good on all supported devices

Fixed Constraints

---

A2D2_iOS/A2D2_iOS/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift
A2D2_iOS/Podfile.lock
A2D2_iOS/Pods/FirebaseCore/Firebase/Core/FIRApp.m
A2D2_iOS/Pods/FirebaseCore/Firebase/Core/FIROptions.m
A2D2_iOS/Pods/FirebaseCore/Firebase/Core/Private/FIRAppInternal.h
A2D2_iOS/Pods/Manifest.lock
A2D2_iOS/Pods/Target Support Files/FirebaseCore/FirebaseCore.xcconfig

Driver login

---

A2D2_iOS/A2D2_iOS/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Info.plist

Make the Views Constrain Properly to Landscape

Updated Constraints; Forced Portrait Only

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj

completed "Fix bundle identifier on master" chore

Changed team to none for master ambiguity

---

A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestOptionsController.swift

Formatted the Phone Number field to display as (xxx) xxx-xxxx. Fixed so the database will take the correct version of the phone number.

Phone number formatting

---

.gitignore
A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS/Controllers/AuthenticationUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/SystemUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/DriverLoginController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestStatusController.swift
A2D2_iOS/A2D2_iOS/ViewControllers/RideRequestDetailsController.swift
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift
A2D2_iOS/Cartfile.resolved
A2D2_iOS/Carthage/Build/.FirebaseAnalyticsBinary.version
A2D2_iOS/Carthage/cartfile
A2D2_iOS/cartfile

Try doing a fresh clone of our repository before we attempt to test and merge to try and see if the dependencies are being properly managed for fresh environments.

Firebase auth

---

A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestOptionsController.swift

There were some bugs that were happening after we merged *4* branches into master at once. I've ironed out the issues, but I want to make sure that my 'new' code makes sense and covers all of our bases. Refer to the commits or Slack for info on which branches were merged into master.

Fixing bugs

---

A2D2_iOS/A2D2_iOS/Views/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard
A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift

I've updated the tests to be a little less fragile. Also, I've added logic to interact with the system alert so we don't have to manually allow location permissions before running our test suite. Please check it out and let me know of any improvements. I plan on splitting up our tests into "rider" tests and "driver" tests to fall more in line with OO principles.

Ui test fix

---

A2D2_iOS/A2D2_iOS/Controllers/AppDelegate.swift
A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RideStatusController.swift

Made the A2D2 phone number to be able to be pulled from the database and called with.

A2D2 phone number now pulled from database

---

A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestStatusController.swift
A2D2_iOS/A2D2_iOS/Models/Request.swift

Generated some requests to test ordering as well

Made Requests sortable, then sorted them within sections

---

A2D2_iOS/A2D2_iOS/Views/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard
A2D2_iOS/A2D2_iOSUITests/A2D2_iOSUITests.swift

Cursors are now set to the system dark text color
Changed in driver login and create ride request

Fix Cursor Color

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS.xcodeproj/xcshareddata/xcschemes/A2D2_iOS.xcscheme
A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RulesViewController.swift
A2D2_iOS/A2D2_iOSTests/A2D2_iOSTests.swift
A2D2_iOS/A2D2_iOSUITests_InvalidLocation/A2D2_iOSUITests_InvalidLocation.swift
A2D2_iOS/A2D2_iOSUITests_InvalidLocation/Info.plist
A2D2_iOS/Cupertino.gpx
A2D2_iOS/MaxwellAFB.gpx

set up tests and requisite testing locations

Checks for location before allowing a request to be made

---

A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

Removed Back Button

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/HomeController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestOptionsController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RideStatusController.swift
A2D2_iOS/A2D2_iOS/Models/Status.swift
A2D2_iOS/A2D2_iOS/Views/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

Added Cancel Button to the ride status page:
it changes ride status to cancelled and returns the user to the Home page

Cancel Button

---

A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/DriverLoginController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RequestOptionsController.swift
A2D2_iOS/A2D2_iOS/Views/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

Fixed the screen not scrolling back to the right location after dismissing the keyboard when creating a ride request
improved focus control for ride request options page and driver login pages
minor code styling

Bugfix and keyboard improvements

---

A2D2_iOS/A2D2_iOS/Views/Driver.storyboard

fixes bug where remarks get cut off; details page now in a scroll view

Driver Reads Long Remark

---

A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/RulesViewController.swift

Tested on device since simulator has no dialer

Adds call button to to location out of range alert

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Driver_LoginController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Driver_RequestListController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Home_Controller.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_CreateRequestController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RequestStatusController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RulesController.swift
A2D2_iOS/A2D2_iOS/ViewControllers/Driver_RequestDetailsController.swift
A2D2_iOS/A2D2_iOS/Views/Base.lproj/Main.storyboard
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

Refactored file names and some minor functionality for ease of development

Refactoring

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS/Controllers/AppDelegate.swift
A2D2_iOS/A2D2_iOS/Controllers/AuthenticationUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Driver_RequestListController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_CreateRequestController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RequestStatusController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RulesController.swift
A2D2_iOS/A2D2_iOS/Models/DataSource.swift
A2D2_iOS/A2D2_iOS/Models/DataSourceDelagate.swift
A2D2_iOS/A2D2_iOS/Models/DataSourceDelegate.swift
A2D2_iOS/A2D2_iOS/Models/Request.swift
A2D2_iOS/A2D2_iOS/ViewControllers/Driver_RequestDetailsController.swift
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

Changes data source to Delegate model

---

A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RequestStatusController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RulesController.swift
A2D2_iOS/A2D2_iOS/Models/DataSource.swift
A2D2_iOS/A2D2_iOS/Views/Rider.storyboard

This simply adjusts the code to accept the databases improved structure; no functional changes.
Also fixed a typo (Issue ID #64)

Database structure

---

A2D2_iOS/A2D2_iOS/Controllers/DataSourceUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Rider_RulesController.swift
A2D2_iOS/A2D2_iOS/Models/DataSource.swift

We changed the database a little so it was optimized for multi-base usage. 
This commit updates the app to read the updated structure. 
No changes to functionality.

Adjusted app to use the multi-base ready database format

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS.xcodeproj/xcshareddata/xcschemes/A2D2_iOS.xcscheme
A2D2_iOS/A2D2_iOS/Info.plist

updated build number and bundle identifier.

Build number update

---

A2D2_iOS/A2D2_iOS.xcodeproj/project.pbxproj
A2D2_iOS/A2D2_iOS.xcodeproj/xcshareddata/xcschemes/A2D2_iOS.xcscheme
A2D2_iOS/A2D2_iOS/Controllers/AuthenticationUtils.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Driver_LoginController.swift
A2D2_iOS/A2D2_iOS/Controllers/ViewControllers/Driver_ResetPasswordController.swift
A2D2_iOS/A2D2_iOS/Info.plist
A2D2_iOS/A2D2_iOS/Views/Driver.storyboard
A2D2_iOS/A2D2_iOSUITests/Driver_Login_Tests.swift

Reset password

---

A2D2_iOS/A2D2_iOS/Info.plist

updated location auth message and build number

Location auth message issue82
